### PR TITLE
Store credentials for multiple users

### PR DESCRIPTION
**Pull request by kenanduman1988**
Auth facade used.

### CODE REVIEW

**Comment by kenanduman1988** [comment]
@dacastro4 please review it

**Comment by dacastro4** [comment]
@kenanduman1988 Will do. Thank you

**Comment by dacastro4** [comment]
@kenanduman1988 you're returning the logged user's ID ` Auth::user()->id ` that doesn't do anything at the time of a request to google, the file contains the `api_token`, `refresh_token` and more information needed and this is only returning the user's Id.

I just want to understand the goal

**Comment by dacastro4** [comment]
Using #61 for this feature. Thanks

**Pull request closed without merging**
