### PR TITLE
Support for additional Google Scopes

### PR DESCRIPTION
**Pull request by salexfo**
Hi Man,

Thank you so much for your repository. Saved me lots of time (so much, that I've even decided to help you with your beer budget  LOL). Anyhow, I think it will be great if you add this PR as it allows to get additional Google scopes with one OAuth request. Without it - the app will have to do multiple OAuth requests to get additional scopes. For instance: if you want to get in addition to the email address the user's first and last name you'll have to do another OAuth 3-legged request after getting the gmail scopes.

### CODE REVIEW

**Comment by dacastro4** [comment]
Hey @salexfo thank you for the support. I understand the problem but I can see that you created a `additionalGoogleScopes` method but that method has no parameters so I don't know where do you set the additional parameters.

I can give you an idea:

Change that parameter logic to and the scopes to:
### src/Traits/Configurable.php
```
protected $additionalScopes;
...
public function setAdditionalScopes( array $scopes )
{
	$this->additionalScopes = $scopes;

	return $this;
}

private function getUserScopes()
{
	$scopes = $this->_config[ 'gmail.scopes' ];

	return array_merge( $scopes, $this->mapScopes(), $this->additionalScopes );
}
```

and add this to the config file.

### src/config/gmail.php
```
...
'scopes' => [
	'readonly',
],
...
```

Sorry, that's what I would do because other way, It doesn't make sense.

**Comment by dacastro4** [comment]
I got your idea and made it right. Thank you for your collaboration!

**Comment by nunomsh** [comment]
I think this issue is not fixed!
After updating from 0.6.0 to 0.6.1 it stop working, and the error is that $this->additionalScopes is not an array (returns null) , so the merge breaks.
I've set the config to 
`'scopes' => [
		'readonly',
	],` 
so scopes is an array, 
The hack to fix this was to add the array direct in the function 
`return array_merge( $scopes, $this->mapScopes(), [] );`

But I think this is not a solution, just to fix my problem..

**Comment by nunomsh** [comment]
After checking the google report, had to change the scope array in the config file (config/gmail.php). Insted of 'modify' I had to use the full url to the scope I want to use

`'scopes' => ['https://www.googleapis.com/auth/gmail.modify',],`

and in Configurable.php

`return array_merge( $scopes, $this->mapScopes(), [] );`

I know this is not the best solution, but a simple fix/hack for others with the same problem

**Comment by dacastro4** [comment]
@nunomsh thank you for notifying. I'll fix it asap.

**Pull request closed without merging**
