### PR TITLE
Decouple user authentication from session

### PR DESCRIPTION
**Pull request by jtwiest**

### CODE REVIEW

**Comment by jtwiest** [comment]
This PR supports the two primary use cases:

1. Send mail as specific user: 
`$mail = new Mail(null, false, $userId);`

2. Set active user on LaravelGmail Facade
`$message = LaravelGmail::setUserId($userId)->message()->preload()->get($someID);`

**Comment by dacastro4** [comment]
@jtwiest don't you think that using `auth()->loginUsingId()` method in your command would have the same result?

**Comment by jtwiest** [comment]
@dacastro4 normally yes but not in the context of a cronjob. My application is automating the sending of emails via a cronjob so there's no session to pull off of.

**Comment by nasatome** [comment]
When a new instance is created `$mail = new Mail(null, false, $userId);` it would not be better to receive an array, 
`$options = ['value1' => 'null', 'value2' => false, 'userId' => $userId]`
`$mail = new Mail($options);`

maybe in a misplaced comment, but I worry that after some values ​​are occupied and others do not, and start sending a lot of null.

would it be good to raise this as an improvement/enhacement?

**Comment by jtwiest** [comment]
@nasatome I do like the idea of using an array here instead but my concern is backward compatibility as the Mail class if a pretty core one to the plugin.

@dacastro4 do you have an opinion here?

**Comment by dacastro4** [comment]
Sorry for the delay guys, very busy at work.

I really like @nasatome idea, it prevents adding used and allow more options in the future if needed.

**Comment by nasatome** [comment]
Who gets that array is a constructor, isn't it?

```
if (is_array($options)){
 // ... Assignment of Variables
} else {
 // ... Normal flow for backward compatibility	
}
```

It's just an idea.

**Comment by tancou** [comment]
> @dacastro4 normally yes but not in the context of a cronjob. My application is automating the sending of emails via a cronjob so there's no session to pull off of.

@jtwiest 
If you use concurrent jobs, be careful with Facade because memory is shared with all jobs.

**Comment by StaleSpace** [comment]
@dacastro4 any timeline for this pull? any workaround for now?

**Comment by dacastro4** [comment]
@StaleSpace I'll merge it this weekend. So sorry that I forgot about this

**Pull request merged**
